# Generated by Django 5.0.4 on 2024-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_borrowbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
