# Generated by Django 5.0.4 on 2024-07-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_borrowbook_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='is_completed',
            new_name='is_returned',
        ),
    ]
